name: Auto_Package

on: [push, pull_request]

jobs:
  release-crx:
    name: Release extension
    runs-on: ubuntu-latest
    steps:
      - name: Download Extension
        uses: actions/checkout@v4

      - name: Install CRX3
        run: yarn global add crx3

      - name: Collect version
        run: |
          echo "BUILD_VERSION=$(sed -nE 's/^\s*"version": "(.*?)",$/\1/p' packages/app/package.json)" >> $GITHUB_ENV
          echo "${{ env.BUILD_VERSION }}"

      - name: Pack Extension
        run: crx3 -o extension.crx ${{ github.workspace }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ github.workspace }}/extension.crx
          asset_name: fuel-wallet-chrome-${{ env.BUILD_VERSION }}.zip
          asset_content_type: application/zip
