name: Auto_Package

on: [push, pull_request]

jobs:
  release-crx:
    name: Release extension
    runs-on: ubuntu-latest
    steps:
      - name: Download Extension
        uses: actions/checkout@v4

      - name: Install CRX3
        run: yarn global add crx3

      - name: Pack Extension
        run: crx3 -o extension.crx .

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./extension/*.crx
          token: ${{ github.token }}
