name: Auto_Package

on: [push, pull_request]

jobs:
  release-crx:
    name: Release extension
    runs-on: ubuntu-latest
    steps:
      - name: Download Extension
        uses: actions/download-artifact@v4
        with:
          name: extension.zip
          path: .

      - name: Install CRX3
        run: yarn global add crx3

      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Pack Extension
        run: crx3 -o extension.crx ./build/

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./extension/*.crx
          token: ${{ github.token }}
