name: Auto_Package

on: [push, pull_request]

jobs:
  release-crx:
    name: Release extension
    runs-on: ubuntu-latest
    steps:
      - name: Download Extension
        uses: actions/checkout@v4

      - name: Install CRX3
        run: npm install -g crx3

      - name: Pack Extension
        run: crx3 -o extension.crx ${{ github.workspace }}

      - name: Create Release
        uses: alexellis/upload-assets@0.4.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["${{ github.workspace }}/*.crx"]'
