name: Auto_Package

on: [push, pull_request]

jobs:
  release-crx:
    name: Release extension
    runs-on: ubuntu-latest
    steps:
      - name: Download Extension
        uses: actions/checkout@v4

      - name: Install CRX3
        run: yarn global add crx3

      - name: Collect Version
        run: |
          echo "BUILD_VERSION=$(sed -nE 's/^\s*"version": "(.*?)",$/\1/p' ${{ github.workspace }}/manifest.json)" >> $GITHUB_ENV

      - name: Pack Extension
        run: crx3 -o extension.crx ${{ github.workspace }}

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.workspace }}/extension.crx
          tag_name: ${{ env.BUILD_VERSION }}
